### ISSUE TITLE
edit Conntrack.py to support version

### ISSUE THREAD

**Issue by hatu90** [ei-grad/python-conntrack#3]
Hi,
I have cloned and edited your patchset and it is luckily working well:
-nfct = c.CDLL(find_library('libnetfilter_conntrack'))
## -libc = c.CDLL(find_library('libc'))

+nfct = c.cdll.LoadLibrary(find_library('netfilter_conntrack'))
+libc = c.cdll.LoadLibrary(find_library('libc.so.6'))

**Comment by ei-grad** [comment]
Thanks, I have fixed it in master.
